var GAME_LEVELS = [
  ["                                                                                ",
   "     x     xxxx x     x xxxx x       xxx                                        ",
   "     x     x    xx   xx x    x       x x                                        ",
   "     x     xxx   xx xx  xxx  x         x                                        ",
   "     x     x      xxx   x    x         x                                        ",
   "     xxxxx xxxx    x    xxxx xxxxx   xxxxx                                      ",
   "                                                                                ",
   "                                                                                ",
   "                              xxxx                  xxxxxxx                     ",
   "                              x!!x                  x!xxx!x                     ",
   "                              x!!x                  xvx xvx                     ",
   "                              xvvx                                              ",
   "               o                                                                ",
   "             oxxx                                o          o                   ",
   "  x        oxxx x                               xxxx   o   xxxx  o           x  ",
   "  x       xxx   x              oo           xxx       xxx       xxx          x  ",
   "  x @    xxx    x o                       x                        xxx     o x  ",
   "  xxxxxxxx      xxx   xxxxxxxxx  xxxxxxxxxxxxxxxxxxxx      xxxxxxx   xxxxxxxxx  ",
   "                  x!!!x       x  x                  x      x                    ",
   "                  xxxxx       x!!x                  x!!!!!!x                    ",
   "                              x!!x                  x!!!!!!x                    ",
   "                              xxxx                  xxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                           xxxx                                                   ",
   "      xxxxxxxxxxx          x    xxxx  x     x xxxx  x      x  x                                                   ",
   "      x  |                 x    x     xx   xx x     x         x                                                   ",
   "      x                    x    xxx    xx xx  xxx   x      xxxx                                                   ",
   "      x                    x    x       xxx   x     x      x                                                      ",
   "      x        xx          xxxx xxxx     x    xxxx  xxxx   xxxx                                                   ",
   "      x    o    x                                                                                                 ",
   "      x    x    x                                                                                                 ",
   "      x        ox                                                                                                 ",
   "      x        xx                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "      x    o    x                                                 xx!!!xxx!!!xxx!!!xxx!!!xxx!!!xxx!!!xx           ",
   "      x    x    x                                                  xvvvx xvvvx xvvvx xvvvx xvvvx xvvvxx           ",
   "      x o       x                                                                                                 ",
   "      x x       x                                           xx                                                    ",
   "      x    o    x                                          xx                                                     ",
   "      x    x    x                                         xx                                                      ",
   "                x         o                              xx                                                       ",
   "             |xxx!!!xx!!!xxx=     o   o     =x     o    xx        o           o           o           o           ",
   "     xxxxxxxxxxxx!!!xx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxx   xxx   xxx   xxx   xxx   xxx   xxx          ",
   " @  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],  
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                x     xxxx x     x xxxx x     xxxx                            ",
   "                            xxxxxxxxx           x     x    xx   xx x    x        x                            ",
   "                          oxx       x       x   x     xxx   xx xx  xxx  x     xxxx                            ",
   "                          xx        x=      x   x     x      xxx   x    x        x                            ",
   "                         xx         x       x   xxxxx xxxx    x    xxxx xxxxx xxxx                            ",
   "                        xx          x      ox                                                                 ",
   "                       xx           x      xx                                                                 ",
   "                      xx            x       x                                                                 ",
   "                     xx             x      =x     xxxxxx    xxxxxx                                            ",
   "                   oxx              x       x     x!xx!x    x!xx!x                                            ",
   "                   xx               x       x     xx!!xx    xx!!xx                                            ",
   "                  xx                x       x     xX| Xx    xx| xx            xxxxxxxxx                       ",
   "                 xx                 xo      x                                xx!!!!!!x                        ",
   "                xx                  xx      x                               xx!!!!!!!x                        ",
   "              oxx                   x=      x                              xx!!!!!!!xx                        ",
   "              xx                    x      =x                  |          xxxx!xxx!xx                         ",
   "             xx                     x                |                   xxx xvxxxvx                          ",
   "            xx                      x                                   xxx                                o  ",
   "           xx                       xxxxxxxxo                      oo  xxx                             xxxxx  ",
   "     @    xx                               xxxxxxxx!!!!x oo x!!!!x    xxx   o   o                    x     x  ",
   "!!!!!xxxxxxxxx                                    xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
